server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: localhost
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  #        use_sql_comments: true # show jpql in console
jwt:
  token:
    secret: secret
logging:
  level:
    org.hibernate.SQL: debug